.decl person(p: symbol)
.decl liquor(l: symbol)
.decl age(p: symbol, a: number)
.decl buys(p: symbol, l: symbol)
.decl attempts_to_buy(p: symbol, l: symbol)
.decl violation(p: symbol, l: symbol)

violation(p, l) :- person(p), liquor(l), age(p, a), a < 18, (buys(p, l); attempts_to_buy(p, l)).
person("student1").
liquor("vodka").
age("student1", 16).
attempts_to_buy("student1", "vodka").
violation("student1", "vodka").
.output violation