.decl person(p: symbol)
.decl liquor(l: symbol)
.decl age(p: symbol, a: number)
.decl buys(p: symbol, l: symbol)
.decl attempts_to_buy(p: symbol, l: symbol)
.decl violation(p: symbol, l: symbol)

violation(p, l) :- person(p), liquor(l), age(p, a), a < 18, (buys(p, l); attempts_to_buy(p, l)).
person("Sarah").
person("Alex").
liquor("alcohol").
age("Sarah", 17).
age("Alex", 19).
buys("Alex", "alcohol").
violation("Sarah", "alcohol").
.output violation