.decl person(p: symbol)
.decl liquor(l: symbol)
.decl age(p: symbol, a: number)
.decl buys(p: symbol, l: symbol)
.decl attempts_to_buy(p: symbol, l: symbol)
.decl violation(p: symbol, l: symbol)

violation(p, l) :- person(p), liquor(l), age(p, a), a < 18, (buys(p, l); attempts_to_buy(p, l)).
person("teen1").
person("teen2").
person("teen3").
liquor("whiskey").
liquor("vodka").
age("teen1", 17).
age("teen2", 16).
age("teen3", 15).
attempts_to_buy("teen1", "whiskey").
attempts_to_buy("teen1", "vodka").
attempts_to_buy("teen2", "whiskey").
attempts_to_buy("teen2", "vodka").
attempts_to_buy("teen3", "whiskey").
attempts_to_buy("teen3", "vodka").
violation("teen1", "whiskey").
violation("teen1", "vodka").
violation("teen2", "whiskey").
violation("teen2", "vodka").
violation("teen3", "whiskey").
violation("teen3", "vodka").
.output violation