.decl person(p: symbol)
.decl liquor(l: symbol)
.decl licensed_premises(lp: symbol)
.decl age(p: symbol, a: number)
.decl buys(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)
.decl violation(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)

violation(buyer, consumer, l, lp) :- person(buyer), person(consumer), liquor(l), licensed_premises(lp), buys(buyer, consumer, l, lp), age(consumer, a), a < 18.
person("mother").
person("son").
person("guest1").
person("guest2").
liquor("non_alcoholic_beer").
licensed_premises("home").
age("son", 16).
age("guest1", 17).
age("guest2", 17).
buys("mother", "son", "non_alcoholic_beer", "home").
buys("mother", "guest1", "non_alcoholic_beer", "home").
buys("mother", "guest2", "non_alcoholic_beer", "home").
.output violation