.decl person(p: symbol)
.decl liquor(l: symbol)
.decl licensed_premises(lp: symbol)
.decl age(p: symbol, a: number)
.decl buys(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)
.decl violation(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)

violation(buyer, consumer, l, lp) :- person(buyer), person(consumer), liquor(l), licensed_premises(lp), buys(buyer, consumer, l, lp), age(consumer, a), a < 18.
person("sarah").
person("sarahs_sister").
licensed_premises("liquor_store").
age("sarahs_sister", 17).
buys("sarah", "sarahs_sister", "non_alcoholic_sparkling_juice", "liquor_store").
.output violation