.decl person(p: symbol)
.decl liquor(l: symbol)
.decl licensed_premises(lp: symbol)
.decl age(p: symbol, a: number)
.decl buys(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)
.decl violation(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)

violation(buyer, consumer, l, lp) :- person(buyer), person(consumer), liquor(l), licensed_premises(lp), buys(buyer, consumer, l, lp), age(consumer, a), a < 18.
person("19yo1").
person("19yo2").
person("17yo").
age("19yo1", 19).
age("19yo2", 19).
age("17yo", 17).
licensed_premises("bar").
buys("19yo1", "17yo", "liquor", "bar").
.output violation