.decl person(p: symbol)
.decl liquor(l: symbol)
.decl licensed_premises(lp: symbol)
.decl age(p: symbol, a: number)
.decl buys(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)
.decl violation(buyer: symbol, consumer: symbol, l: symbol, lp: symbol)

violation(buyer, consumer, l, lp) :- person(buyer), person(consumer), liquor(l), licensed_premises(lp), buys(buyer, consumer, l, lp), age(consumer, a), a < 18.
person("parent").
person("child").
age("child", 16).
licensed_premises("local_bar").
buys("parent", "child", "non_alcoholic_drink", "local_bar").
.output violation