.decl premise(pr: symbol)
.decl licensed_premise(pr: symbol)
.decl notice(n: symbol)
.decl age_restriction(n: symbol)
.decl trading_hour(n: symbol)

.decl required(pr: symbol, n: symbol)
.decl display(pr: symbol, n: symbol)
.decl violation(pr: symbol, n: symbol)

violation(pr, n) :- licensed_premise(pr), notice(n), (age_restriction(n);trading_hour(n)), required(pr, n), !display(pr, n).
licensed_premise("nightclub").
notice("trading_hours_notice").
notice("age_restriction_notice").
age_restriction("age_restriction_notice").
trading_hour("trading_hours_notice").
required("nightclub", "trading_hours_notice").
required("nightclub", "age_restriction_notice").
violation("nightclub", "trading_hours_notice").
violation("nightclub", "age_restriction_notice").
.output violation