.decl employer(e: symbol)
.decl waitress(w: symbol)
.decl employs(e: symbol, w: symbol)
.decl age(w: symbol, a: number)
.decl known_prostitute(w: symbol)
.decl bad_character(w: symbol)
.decl violation(e: symbol, w: symbol, a: number)

violation(e, w, a) :- employer(e), waitress(w), employs(e, w), age(w, a), a < 17.
violation(e, w, 0) :- employer(e), waitress(w), employs(e, w), (known_prostitute(w); bad_character(w)).
employer("nightclub_owner").
waitress("new_waitress").
employs("nightclub_owner", "new_waitress").
age("new_waitress", 18).
.output violation