.decl person(p: symbol)
.decl buys_online(p: symbol)
.decl age(p: symbol, a: number)
.decl warned(p: symbol)
.decl informed_of_penalty(p: symbol)
.decl violation(p: symbol, a: number)

violation(p, a) :- person(p), buys_online(p), age(p, a), a < 18, (!warned(p); !informed_of_penalty(p)).
person("young_adult").
buys_online("young_adult").
age("young_adult", 17).
violation("young_adult", 17).
.output violation