.decl person(p: symbol)
.decl buys_online(p: symbol)
.decl age(p: symbol, a: number)
.decl warned(p: symbol)
.decl informed_of_penalty(p: symbol)
.decl violation(p: symbol, a: number)

violation(p, a) :- person(p), buys_online(p), age(p, a), a < 18, (!warned(p); !informed_of_penalty(p)).
person("Alice").
buys_online("Alice").
age("Alice", 20).
person("Bob").
buys_online("Bob").
age("Bob", 17).
person("Charlie").
buys_online("Charlie").
age("Charlie", 18).
.output violation