.decl person(p: symbol)
.decl liquor(l: symbol)
.decl platform(pl: symbol)
.decl supplies(p: symbol, l: symbol, pl: symbol)
.decl verifies_age(pl: symbol)
.decl warns_underage(pl: symbol)
.decl informs_penalties(pl: symbol)
.decl violation(p: symbol, l: symbol, pl: symbol)

violation(p, l, pl) :- person(p), liquor(l), platform(pl), supplies(p, l, pl),(!verifies_age(pl); !warns_underage(pl); !informs_penalties(pl)).
person("customer1").
person("customer2").
liquor("beer").
liquor("wine").
liquor("whiskey").
platform("online_grocery_store").
supplies("customer1", "beer", "online_grocery_store").
supplies("customer2", "wine", "online_grocery_store").
verifies_age("online_grocery_store").
warns_underage("online_grocery_store").
informs_penalties("online_grocery_store").
.output violation