.decl person(p: symbol)
.decl liquor(l: symbol)
.decl platform(pl: symbol)
.decl supplies(p: symbol, l: symbol, pl: symbol)
.decl verifies_age(pl: symbol)
.decl warns_underage(pl: symbol)
.decl informs_penalties(pl: symbol)
.decl violation(p: symbol, l: symbol, pl: symbol)

violation(p, l, pl) :- person(p), liquor(l), platform(pl), supplies(p, l, pl),(!verifies_age(pl); !warns_underage(pl); !informs_penalties(pl)).
person("customer").
liquor("signature_cocktail").
platform("FoodDeliveryApp").
supplies("customer", "signature_cocktail", "FoodDeliveryApp").
verifies_age("FoodDeliveryApp").
warns_underage("FoodDeliveryApp").
informs_penalties("FoodDeliveryApp").
.output violation