.decl person(p: symbol)
.decl license_holder(h: symbol)
.decl licensed_premises(l: symbol)
.decl age(p: symbol, a: number)
.decl consumes(p: symbol, l: symbol)
.decl permits(h: symbol, p: symbol, l: symbol)
.decl violation(h: symbol, p: symbol, l: symbol)

violation(h, p, l) :- person(p), license_holder(h), licensed_premises(l), age(p, a), a < 18, consumes(p, l), permits(h, p, l).
person("parent1").
person("parent2").
person("daughter").
license_holder("parent1").
license_holder("parent2").
licensed_premises("pub").
age("daughter", 16).
consumes("daughter", "pub").
permits("parent1", "daughter", "pub").
permits("parent2", "daughter", "pub").
.output violation