.decl person(p: symbol)
.decl license_holder(h: symbol)
.decl licensed_premises(l: symbol)
.decl age(p: symbol, a: number)
.decl consumes(p: symbol, l: symbol)
.decl permits(h: symbol, p: symbol, l: symbol)
.decl violation(h: symbol, p: symbol, l: symbol)

violation(h, p, l) :- person(p), license_holder(h), licensed_premises(l), age(p, a), a < 18, consumes(p, l), permits(h, p, l).
person("teen1").
person("teen2").
person("teen3").
person("adult1").
license_holder("adult1").
licensed_premises("house1").
age("teen1", 17).
age("teen2", 17).
age("teen3", 17).
consumes("teen1", "house1").
consumes("teen2", "house1").
consumes("teen3", "house1").
permits("adult1", "teen1", "house1").
permits("adult1", "teen2", "house1").
permits("adult1", "teen3", "house1").
.output violation