.decl person(p: symbol)
.decl license_holder(h: symbol)
.decl licensed_premises(l: symbol)
.decl age(p: symbol, a: number)
.decl consumes(p: symbol, l: symbol)
.decl permits(h: symbol, p: symbol, l: symbol)
.decl violation(h: symbol, p: symbol, l: symbol)

violation(h, p, l) :- person(p), license_holder(h), licensed_premises(l), age(p, a), a < 18, consumes(p, l), permits(h, p, l).
person("student1").
person("student2").
person("student3").
person("bartender1").
license_holder("bartender1").
licensed_premises("bar1").
age("student1", 17).
age("student2", 17).
age("student3", 17).
consumes("student1", "bar1").
consumes("student2", "bar1").
consumes("student3", "bar1").
permits("bartender1", "student1", "bar1").
permits("bartender1", "student2", "bar1").
permits("bartender1", "student3", "bar1").
.output violation