.decl person(p: symbol)
.decl premises(pr: symbol)
.decl licensed_premises(pr: symbol)
.decl permits(p: symbol, pr: symbol)
.decl drunk_behavior(q: symbol, pr: symbol)
.decl disorderly_behavior(q: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), licensed_premises(pr), permits(p, pr), (drunk_behavior(q, pr); disorderly_behavior(q, pr)).
person("friend1").
person("friend2").
premises("restaurant1").
licensed_premises("restaurant1").
permits("friend1", "restaurant1").
permits("friend2", "restaurant1").
disorderly_behavior("friend1", "restaurant1").
disorderly_behavior("friend2", "restaurant1").
.output violation