.decl person(p: symbol)
.decl equipment(e: symbol)
.decl mechanical(e: symbol)
.decl electrical(e: symbol)
.decl tampers(p: symbol, e: symbol)
.decl damages(p: symbol, e: symbol)
.decl violation(p: symbol, e: symbol)

violation(p, e) :- person(p), equipment(e), (tampers(p, e); damages(p, e)), (mechanical(e); electrical(e)).
person("commuter1").
equipment("ticketing_machine1").
electrical("ticketing_machine1").
tampers("commuter1", "ticketing_machine1").
violation("commuter1", "ticketing_machine1").
.output violation