.decl person(p: symbol)
.decl equipment(e: symbol)
.decl mechanical(e: symbol)
.decl electrical(e: symbol)
.decl tampers(p: symbol, e: symbol)
.decl damages(p: symbol, e: symbol)
.decl violation(p: symbol, e: symbol)

violation(p, e) :- person(p), equipment(e), (tampers(p, e); damages(p, e)), (mechanical(e); electrical(e)).
person("teenager").
equipment("escalator").
mechanical("escalator").
electrical("escalator").
tampers("teenager", "escalator").
damages("teenager", "escalator").
violation("teenager", "escalator").
.output violation