.decl person(p: symbol)
.decl equipment(e: symbol)
.decl mechanical(e: symbol)
.decl electrical(e: symbol)
.decl tampers(p: symbol, e: symbol)
.decl damages(p: symbol, e: symbol)
.decl violation(p: symbol, e: symbol)

violation(p, e) :- person(p), equipment(e), (tampers(p, e); damages(p, e)), (mechanical(e); electrical(e)).
person("teen1").
equipment("escalator1").
mechanical("escalator1").
tampers("teen1", "escalator1").
damages("teen1", "escalator1").
violation("teen1", "escalator1").
.output violation