.decl person(p: symbol)
.decl equipment(e: symbol)
.decl mechanical(e: symbol)
.decl electrical(e: symbol)
.decl tampers(p: symbol, e: symbol)
.decl damages(p: symbol, e: symbol)
.decl violation(p: symbol, e: symbol)

violation(p, e) :- person(p), equipment(e), (tampers(p, e); damages(p, e)), (mechanical(e); electrical(e)).
person("maintenance_worker").
equipment("train_braking_system").
mechanical("train_braking_system").
tampers("maintenance_worker", "train_braking_system").
damages("maintenance_worker", "train_braking_system").
violation("maintenance_worker", "train_braking_system").
.output violation