.decl person(p: symbol)
.decl device(d: symbol)
.decl escalator(d: symbol)
.decl travelator(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (escalator(d); travelator(d)).
person("teenager1").
person("teenager2").
device("escalator").
escalator("escalator").
misuses("teenager1", "escalator").
misuses("teenager2", "escalator").
violation("teenager1", "escalator").
violation("teenager2", "escalator").
.output violation