.decl person(p: symbol)
.decl device(d: symbol)
.decl escalator(d: symbol)
.decl travelator(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (escalator(d); travelator(d)).
person("man_in_suit").
device("escalator").
escalator("escalator").
misuses("man_in_suit", "escalator").
violation("man_in_suit", "escalator").
.output violation