.decl person(p: symbol)
.decl device(d: symbol)
.decl escalator(d: symbol)
.decl travelator(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (escalator(d); travelator(d)).
person("man_with_bicycle").
device("escalator1").
escalator("escalator1").
misuses("man_with_bicycle", "escalator1").
violation("man_with_bicycle", "escalator1").
.output violation