.decl person(p: symbol)
.decl device(d: symbol)
.decl escalator(d: symbol)
.decl travelator(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (escalator(d); travelator(d)).
person("child1").
device("escalator1").
escalator("escalator1").
misuses("child1", "escalator1").
violation("child1", "escalator1").
.output violation