.decl person(p: symbol)
.decl device(d: symbol)
.decl emergency_device(d: symbol)
.decl safety_device(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (emergency_device(d); safety_device(d)).
person("teenager1").
person("teenager2").
device("fire_alarm").
emergency_device("fire_alarm").
misuses("teenager1", "fire_alarm").
misuses("teenager2", "fire_alarm").
violation("teenager1", "fire_alarm").
violation("teenager2", "fire_alarm").
.output violation