.decl person(p: symbol)
.decl device(d: symbol)
.decl emergency_device(d: symbol)
.decl safety_device(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (emergency_device(d); safety_device(d)).
person("passenger1").
device("emergency_services").
emergency_device("emergency_services").
misuses("passenger1", "emergency_services").
violation("passenger1", "emergency_services").
.output violation