.decl person(p: symbol)
.decl device(d: symbol)
.decl emergency_device(d: symbol)
.decl safety_device(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (emergency_device(d); safety_device(d)).
person("teenager1").
person("teenager2").
person("teenager3").
device("emergency_brake").
emergency_device("emergency_brake").
misuses("teenager1", "emergency_brake").
misuses("teenager2", "emergency_brake").
misuses("teenager3", "emergency_brake").
violation("teenager1", "emergency_brake").
violation("teenager2", "emergency_brake").
violation("teenager3", "emergency_brake").
.output violation