.decl person(p: symbol)
.decl device(d: symbol)
.decl emergency_device(d: symbol)
.decl safety_device(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (emergency_device(d); safety_device(d)).
person("teenager").
device("fire_alarm").
safety_device("fire_alarm").
misuses("teenager", "fire_alarm").
violation("teenager", "fire_alarm").
.output violation