.decl person(p: symbol)
.decl device(d: symbol)
.decl emergency_device(d: symbol)
.decl safety_device(d: symbol)
.decl misuses(p: symbol, d: symbol)
.decl violation(p: symbol, d: symbol)

violation(p, d) :- person(p), device(d), misuses(p, d), (emergency_device(d); safety_device(d)).
person("teenager").
device("elevator_emergency_button").
emergency_device("elevator_emergency_button").
misuses("teenager", "elevator_emergency_button").
violation("teenager", "elevator_emergency_button").
.output violation