.decl person(p: symbol)
.decl railway_property(rp: symbol)
.decl defaces(p: symbol, rp: symbol)
.decl damages(p: symbol, rp: symbol)
.decl improperly_removes(p: symbol, rp: symbol)
.decl violation(p: symbol, rp: symbol)

violation(p, rp) :- person(p), railway_property(rp), (defaces(p, rp); damages(p, rp); improperly_removes(p, rp)).
person("teenager_group").
railway_property("train_seats").
defaces("teenager_group", "train_seats").
improperly_removes("teenager_group", "train_seats").
.output violation