.decl person(p: symbol)
.decl railway_property(rp: symbol)
.decl defaces(p: symbol, rp: symbol)
.decl damages(p: symbol, rp: symbol)
.decl improperly_removes(p: symbol, rp: symbol)
.decl violation(p: symbol, rp: symbol)

violation(p, rp) :- person(p), railway_property(rp), (defaces(p, rp); damages(p, rp); improperly_removes(p, rp)).
person("man1").
railway_property("display_screen").
damages("man1", "display_screen").
violation("man1", "display_screen").
.output violation