.decl person(p: symbol)
.decl railway_property(rp: symbol)
.decl defaces(p: symbol, rp: symbol)
.decl damages(p: symbol, rp: symbol)
.decl improperly_removes(p: symbol, rp: symbol)
.decl violation(p: symbol, rp: symbol)

violation(p, rp) :- person(p), railway_property(rp), (defaces(p, rp); damages(p, rp); improperly_removes(p, rp)).
person("individual1").
railway_property("ticketing_machines").
damages("individual1", "ticketing_machines").
violation("individual1", "ticketing_machines").
.output violation