.decl person(p: symbol)
.decl premises(pr: symbol)
.decl enters(p: symbol, pr: symbol)
.decl remains(p: symbol, pr: symbol)
.decl intoxicated(p: symbol)
.decl under_influence(p: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), (intoxicated(p); under_influence(p)).
person("friend1").
person("friend2").
person("friend3").
premises("concert").
premises("train_station").
enters("friend1", "concert").
enters("friend2", "concert").
enters("friend3", "concert").
enters("friend1", "train_station").
enters("friend2", "train_station").
enters("friend3", "train_station").
remains("friend1", "concert").
remains("friend2", "concert").
remains("friend3", "concert").
remains("friend1", "train_station").
remains("friend2", "train_station").
remains("friend3", "train_station").
under_influence("friend1").
under_influence("friend2").
under_influence("friend3").
violation("friend1", "concert").
violation("friend2", "concert").
violation("friend3", "concert").
violation("friend1", "train_station").
violation("friend2", "train_station").
violation("friend3", "train_station").
.output violation