.decl person(p: symbol)
.decl premises(pr: symbol)
.decl enters(p: symbol, pr: symbol)
.decl remains(p: symbol, pr: symbol)
.decl intoxicated(p: symbol)
.decl under_influence(p: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), (intoxicated(p); under_influence(p)).
person("Sarah").
premises("MusicFestival").
premises("Train").
premises("TrainStation").
enters("Sarah", "MusicFestival").
enters("Sarah", "Train").
enters("Sarah", "TrainStation").
under_influence("Sarah").
.output violation