.decl person(p: symbol)
.decl premises(pr: symbol)
.decl enters(p: symbol, pr: symbol)
.decl remains(p: symbol, pr: symbol)
.decl unfit_condition(p: symbol)
.decl clothing(p: symbol, c: symbol)
.decl causes_soiling(c: symbol)
.decl causes_damage(c: symbol)
.decl causes_injury(c: symbol)
.decl violation(p: symbol, pr: symbol, c: symbol)

violation(p, pr, "_") :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), unfit_condition(p).
violation(p, pr, c) :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), clothing(p, c), (causes_soiling(c); causes_damage(c); causes_injury(c)).
person("passenger1").
premises("platform1").
premises("train1").
enters("passenger1", "platform1").
enters("passenger1", "train1").
unfit_condition("passenger1").
clothing("passenger1", "backpack1").
causes_soiling("backpack1").
causes_damage("backpack1").
causes_injury("backpack1").
.output violation