.decl person(p: symbol)
.decl premises(pr: symbol)
.decl enters(p: symbol, pr: symbol)
.decl remains(p: symbol, pr: symbol)
.decl unfit_condition(p: symbol)
.decl clothing(p: symbol, c: symbol)
.decl causes_soiling(c: symbol)
.decl causes_damage(c: symbol)
.decl causes_injury(c: symbol)
.decl violation(p: symbol, pr: symbol, c: symbol)

violation(p, pr, "_") :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), unfit_condition(p).
violation(p, pr, c) :- person(p), premises(pr), (enters(p, pr); remains(p, pr)), clothing(p, c), (causes_soiling(c); causes_damage(c); causes_injury(c)).
person("worker1").
person("worker2").
person("worker3").
premises("train_station").
enters("worker1", "train_station").
enters("worker2", "train_station").
enters("worker3", "train_station").
clothing("worker1", "clothing1").
clothing("worker2", "clothing1").
clothing("worker3", "clothing1").
causes_soiling("clothing1").
causes_damage("clothing1").
.output violation