.decl person(p: symbol)
.decl area(a: symbol)
.decl designated_area(a: symbol)
.decl consumes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), consumes(p, a), !designated_area(a).
person("commuter").
person("transit_officer").
area("MRT_train").
designated_area("MRT_train").
consumes("commuter", "MRT_train").
violation("commuter", "MRT_train").
.output violation