.decl person(p: symbol)
.decl premises(pr: symbol)
.decl spits(p: symbol, pr: symbol)
.decl litters(p: symbol, pr: symbol)
.decl soils(p: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), (spits(p, pr); litters(p, pr); soils(p, pr)).
person("commuter1").
premises("train_station").
spits("commuter1", "train_station").
violation("commuter1", "train_station").
.output violation