.decl person(p: symbol)
.decl premises(pr: symbol)
.decl loiters(p: symbol, pr: symbol)
.decl passenger(p: symbol)
.decl has_legitimate_business(p: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), loiters(p, pr), (!passenger(p); !has_legitimate_business(pr)).
person("man_in_thirties").
premises("train_station").
loiters("man_in_thirties", "train_station").
violation("man_in_thirties", "train_station").
.output violation