.decl person(p: symbol)
.decl premises(pr: symbol)
.decl loiters(p: symbol, pr: symbol)
.decl passenger(p: symbol)
.decl has_legitimate_business(p: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), loiters(p, pr), (!passenger(p); !has_legitimate_business(pr)).
person("man").
premises("train_platform").
loiters("man", "train_platform").
violation("man", "train_platform").
.output violation