.decl person(p: symbol)
.decl premises(pr: symbol)
.decl loiters(p: symbol, pr: symbol)
.decl passenger(p: symbol)
.decl has_legitimate_business(p: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), loiters(p, pr), (!passenger(p); !has_legitimate_business(pr)).
person("teen1").
person("teen2").
person("teen3").
premises("train_station").
loiters("teen1", "train_station").
loiters("teen2", "train_station").
loiters("teen3", "train_station").
.output violation