.decl person(p: symbol)
.decl object(o: symbol)
.decl causes_injury(o: symbol)
.decl causes_damage(o: symbol)
.decl throws(p: symbol, o: symbol)
.decl violation(p: symbol, o: symbol)

violation(p, o) :- person(p), object(o), throws(p, o), (causes_injury(o); causes_damage(o)).
person("teenager1").
person("teenager2").
person("teenager3").
object("pebble").
object("platform_screen_door").
throws("teenager1", "pebble").
throws("teenager2", "pebble").
throws("teenager3", "pebble").
causes_damage("pebble").
.output violation