.decl person(p: symbol)
.decl area(a: symbol)
.decl train_area(a: symbol)
.decl meant_for_passengers(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), train_area(a), enters(p, a), !meant_for_passengers(a).
person("tourist").
area("train_tracks").
train_area("train_tracks").
enters("tourist", "train_tracks").
violation("tourist", "train_tracks").
.output violation