.decl person(p: symbol)
.decl area(a: symbol)
.decl train_area(a: symbol)
.decl meant_for_passengers(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), train_area(a), enters(p, a), !meant_for_passengers(a).
person("person1").
area("train_tracks").
train_area("train_area1").
meant_for_passengers("train_area1").
enters("person1", "train_tracks").
violation("person1", "train_tracks").
.output violation