.decl person(p: symbol)
.decl area(a: symbol)
.decl train_area(a: symbol)
.decl meant_for_passengers(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), train_area(a), enters(p, a), !meant_for_passengers(a).
person("teenager1").
person("teenager2").
person("teenager3").
area("path1").
train_area("train_area1").
enters("teenager1", "path1").
enters("teenager2", "path1").
enters("teenager3", "path1").
violation("teenager1", "path1").
violation("teenager2", "path1").
violation("teenager3", "path1").
.output violation