.decl person(p: symbol)
.decl area(a: symbol)
.decl train_area(a: symbol)
.decl meant_for_passengers(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), train_area(a), enters(p, a), !meant_for_passengers(a).
person("teenager1").
person("teenager2").
person("teenager3").
area("train_tunnels").
train_area("train_tunnels").
meant_for_passengers("train_tunnels").
enters("teenager1", "train_tunnels").
enters("teenager2", "train_tunnels").
enters("teenager3", "train_tunnels").
violation("teenager1", "train_tunnels").
violation("teenager2", "train_tunnels").
violation("teenager3", "train_tunnels").
.output violation