.decl person(p: symbol)
.decl area(a: symbol)
.decl train_area(a: symbol)
.decl meant_for_passengers(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), train_area(a), enters(p, a), !meant_for_passengers(a).
person("friend1").
person("friend2").
person("friend3").
area("maintenance_tunnels").
train_area("maintenance_tunnels").
enters("friend1", "maintenance_tunnels").
enters("friend2", "maintenance_tunnels").
enters("friend3", "maintenance_tunnels").
.output violation