.decl person(p: symbol)
.decl area(a: symbol)
.decl public_area(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl leaves(p: symbol, a: symbol)
.decl uses_designated_means(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !public_area(a).
violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !uses_designated_means(p, a).
person("passenger1").
area("platform").
public_area("platform").
enters("passenger1", "platform").
uses_designated_means("passenger1", "platform").
.output violation