.decl person(p: symbol)
.decl area(a: symbol)
.decl public_area(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl leaves(p: symbol, a: symbol)
.decl uses_designated_means(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !public_area(a).
violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !uses_designated_means(p, a).
person("individual1").
area("construction_site").
enters("individual1", "construction_site").
.output violation