.decl person(p: symbol)
.decl area(a: symbol)
.decl public_area(a: symbol)
.decl enters(p: symbol, a: symbol)
.decl leaves(p: symbol, a: symbol)
.decl uses_designated_means(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !public_area(a).
violation(p, a) :- person(p), area(a), (enters(p, a); leaves(p, a)), !uses_designated_means(p, a).
person("Emily").
area("train_station").
area("train").
public_area("train_station").
enters("Emily", "train_station").
leaves("Emily", "train_station").
enters("Emily", "train").
leaves("Emily", "train").
uses_designated_means("Emily", "train").
.output violation