.decl person(p: symbol)
.decl area(a: symbol)
.decl prohibited_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), prohibited_area(a), smokes(p, a).
person("commuter").
person("passenger1").
person("passenger2").
person("security1").
area("train_platform").
area("designated_smoking_area").
prohibited_area("train_platform").
smokes("commuter", "train_platform").
.output violation