.decl person(p: symbol)
.decl area(a: symbol)
.decl prohibited_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), prohibited_area(a), smokes(p, a).
person("tourist1").
person("tourist2").
area("train_cabin").
prohibited_area("train_cabin").
smokes("tourist1", "train_cabin").
smokes("tourist2", "train_cabin").
.output violation