.decl person(p: symbol)
.decl animal(a: symbol)
.decl premises(pr: symbol)
.decl brings(p: symbol, a: symbol, pr: symbol)
.decl service_animal(a: symbol)
.decl violation(p: symbol, a: symbol, pr: symbol)

violation(p, a, pr) :- person(p), animal(a), premises(pr), brings(p, a, pr), !service_animal(a).
person("man1").
animal("python1").
premises("train_platform").
brings("man1", "python1", "train_platform").
violation("man1", "python1", "train_platform").
.output violation