.decl person(p: symbol)
.decl animal(a: symbol)
.decl premises(pr: symbol)
.decl brings(p: symbol, a: symbol, pr: symbol)
.decl service_animal(a: symbol)
.decl violation(p: symbol, a: symbol, pr: symbol)

violation(p, a, pr) :- person(p), animal(a), premises(pr), brings(p, a, pr), !service_animal(a).
person("passenger").
animal("dog").
premises("MRT_station").
brings("passenger", "dog", "MRT_station").
violation("passenger", "dog", "MRT_station").
.output violation