.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("construction_worker").
substance("gasoline").
dangerous("gasoline").
flammable("gasoline").
brings("construction_worker", "gasoline").
.output violation