.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("man1").
substance("propane").
flammable("propane").
brings("man1", "propane").
violation("man1", "propane").
.output violation