.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("man_in_red_white").
substance("fireworks").
dangerous("fireworks").
flammable("fireworks").
brings("man_in_red_white", "fireworks").
violation("man_in_red_white", "fireworks").
.output violation