.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("man_with_box").
substance("explosives").
dangerous("explosives").
flammable("explosives").
brings("man_with_box", "explosives").
violation("man_with_box", "explosives").
.output violation