.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("man1").
substance("matches").
flammable("matches").
brings("man1", "matches").
violation("man1", "matches").
.output violation