.decl person(p: symbol)
.decl substance(s: symbol)
.decl dangerous(s: symbol)
.decl flammable(s: symbol)
.decl brings(p: symbol, s: symbol)
.decl violation(p: symbol, s: symbol)

violation(p, s) :- person(p), substance(s), brings(p, s), (dangerous(s); flammable(s)).
person("passenger1").
substance("chemical1").
dangerous("chemical1").
brings("passenger1", "chemical1").
violation("passenger1", "chemical1").
.output violation