.decl person(p: symbol)
.decl premises(pr: symbol)
.decl matter(m: symbol)
.decl sewage(m: symbol)
.decl waste(m: symbol)
.decl offensive_matter(m: symbol)
.decl causes_entry(p: symbol, m: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), causes_entry(p, m, pr), (sewage(m); waste(m); offensive_matter(m)).
person("passenger1").
premises("train_tracks").
waste("fast_food_wrappers").
causes_entry("passenger1", "fast_food_wrappers", "train_tracks").
violation("passenger1", "train_tracks").
.output violation