.decl person(p: symbol)
.decl premises(pr: symbol)
.decl matter(m: symbol)
.decl sewage(m: symbol)
.decl waste(m: symbol)
.decl offensive_matter(m: symbol)
.decl causes_entry(p: symbol, m: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), causes_entry(p, m, pr), (sewage(m); waste(m); offensive_matter(m)).
person("maintenance_worker").
premises("station_platform").
sewage("sewage").
causes_entry("maintenance_worker", "sewage", "station_platform").
violation("maintenance_worker", "station_platform").
.output violation