.decl person(p: symbol)
.decl notice(n: symbol)
.decl sign(s: symbol)
.decl direction(d: symbol)
.decl authorized_person(ap: symbol)
.decl issues(ap: symbol, n: symbol)
.decl complies(p: symbol, n: symbol)
.decl violation(p: symbol, n: symbol)

violation(p, n) :- person(p), person(ap), (sign(n); notice(n); direction(n)), authorized_person(ap), issues(ap, n), !complies(p, n).
person("curious_individual").
sign("do_not_enter_sign").
authorized_person("authorized_person1").
issues("authorized_person1", "do_not_enter_sign").
violation("curious_individual", "do_not_enter_sign").
.output violation