.decl person(p: symbol)
.decl notice(n: symbol)
.decl sign(s: symbol)
.decl direction(d: symbol)
.decl authorized_person(ap: symbol)
.decl issues(ap: symbol, n: symbol)
.decl complies(p: symbol, n: symbol)
.decl violation(p: symbol, n: symbol)

violation(p, n) :- person(p), person(ap), (sign(n); notice(n); direction(n)), authorized_person(ap), issues(ap, n), !complies(p, n).
person("staff_member").
person("passenger").
authorized_person("staff_member").
direction("move_away_from_doors").
issues("staff_member", "move_away_from_doors").
violation("passenger", "move_away_from_doors").
.output violation