.decl person(p: symbol)
.decl train(t: symbol)
.decl enters(p: symbol, t: symbol)
.decl remains(p: symbol, t: symbol)
.decl is_full(t: symbol)
.decl violation(p: symbol, t: symbol)

violation(p, t) :- person(p), train(t), (enters(p, t); remains(p, t)), is_full(t).
person("parent").
train("train1").
enters("parent", "train1").
remains("parent", "train1").
is_full("train1").
violation("parent", "train1").
.output violation