.decl person(p: symbol)
.decl train(t: symbol)
.decl enters(p: symbol, t: symbol)
.decl remains(p: symbol, t: symbol)
.decl is_full(t: symbol)
.decl violation(p: symbol, t: symbol)

violation(p, t) :- person(p), train(t), (enters(p, t); remains(p, t)), is_full(t).
person("person1").
person("person2").
train("train1").
enters("person1", "train1").
enters("person2", "train1").
is_full("train1").
violation("person1", "train1").
violation("person2", "train1").
.output violation