.decl person(p: symbol)
.decl property(prop: symbol)
.decl authorized_person(p: symbol)
.decl finds(p: symbol, prop: symbol)
.decl hands_over(p: symbol, prop: symbol, ap: symbol)
.decl violation(p: symbol, prop: symbol, ap: symbol)

violation(p, prop, ap) :- person(p), person(ap), property(prop), finds(p, prop), hands_over(p, prop, ap), !authorized_person(ap).
person("Sarah").
property("phone").
finds("Sarah", "phone").
hands_over("Sarah", "phone", "Sarah").
.output violation