.decl person(p: symbol)
.decl property(prop: symbol)
.decl authorized_person(p: symbol)
.decl finds(p: symbol, prop: symbol)
.decl hands_over(p: symbol, prop: symbol, ap: symbol)
.decl violation(p: symbol, prop: symbol, ap: symbol)

violation(p, prop, ap) :- person(p), person(ap), property(prop), finds(p, prop), hands_over(p, prop, ap), !authorized_person(ap).
person("Jane").
property("smartphone").
finds("Jane", "smartphone").
hands_over("Jane", "smartphone", "Jane").
authorized_person("station_staff").
violation("Jane", "smartphone", "Jane").
.output violation