.decl person(p: symbol)
.decl property(prop: symbol)
.decl authorized_person(p: symbol)
.decl finds(p: symbol, prop: symbol)
.decl hands_over(p: symbol, prop: symbol, ap: symbol)
.decl violation(p: symbol, prop: symbol, ap: symbol)

violation(p, prop, ap) :- person(p), person(ap), property(prop), finds(p, prop), hands_over(p, prop, ap), !authorized_person(ap).
person("John").
property("phone").
finds("John", "phone").
person("owner").
authorized_person("owner").
violation("John", "phone", "owner").
.output violation