.decl person(p: symbol)
.decl premises(pr: symbol)
.decl property(prop: symbol)
.decl found_property(prop: symbol)
.decl removes(p: symbol, prop: symbol, pr: symbol)
.decl authorized(p: symbol)
.decl violation(p: symbol, prop: symbol, pr: symbol)

violation(p, prop, pr) :- person(p), premises(pr), property(prop), found_property(prop), removes(p, prop, pr), !authorized(p).
person("passenger1").
premises("station").
property("phone").
found_property("phone").
removes("passenger1", "phone", "station").
violation("passenger1", "phone", "station").
.output violation