.decl person(p: symbol)
.decl premises(pr: symbol)
.decl property(prop: symbol)
.decl found_property(prop: symbol)
.decl removes(p: symbol, prop: symbol, pr: symbol)
.decl authorized(p: symbol)
.decl violation(p: symbol, prop: symbol, pr: symbol)

violation(p, prop, pr) :- person(p), premises(pr), property(prop), found_property(prop), removes(p, prop, pr), !authorized(p).
person("John").
premises("train_station").
property("bag").
found_property("bag").
removes("John", "bag", "train_station").
violation("John", "bag", "train_station").
.output violation