.decl person(p: symbol)
.decl premises(pr: symbol)
.decl property(prop: symbol)
.decl found_property(prop: symbol)
.decl removes(p: symbol, prop: symbol, pr: symbol)
.decl authorized(p: symbol)
.decl violation(p: symbol, prop: symbol, pr: symbol)

violation(p, prop, pr) :- person(p), premises(pr), property(prop), found_property(prop), removes(p, prop, pr), !authorized(p).
person("Sarah").
premises("train_station").
property("wallet").
found_property("wallet").
removes("Sarah", "money", "train_station").
violation("Sarah", "money", "train_station").
.output violation