.decl person(p: symbol)
.decl premises(pr: symbol)
.decl property(prop: symbol)
.decl found_property(prop: symbol)
.decl removes(p: symbol, prop: symbol, pr: symbol)
.decl authorized(p: symbol)
.decl violation(p: symbol, prop: symbol, pr: symbol)

violation(p, prop, pr) :- person(p), premises(pr), property(prop), found_property(prop), removes(p, prop, pr), !authorized(p).
person("Sarah").
premises("train").
property("phone").
found_property("phone").
removes("Sarah", "phone", "train").
.output violation