.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("friend1").
person("friend2").
person("friend3").
article("bag1").
article("bag2").
area("emergency_exit").
area("proper_entrance").
paid_area("proper_entrance").
unpaid_area("emergency_exit").
transfers("friend1", "bag1", "emergency_exit", "proper_entrance").
transfers("friend1", "bag2", "emergency_exit", "proper_entrance").
transfers("friend2", "bag1", "emergency_exit", "proper_entrance").
transfers("friend2", "bag2", "emergency_exit", "proper_entrance").
transfers("friend3", "bag1", "emergency_exit", "proper_entrance").
transfers("friend3", "bag2", "emergency_exit", "proper_entrance").
uses_ticket_gate("friend1", "emergency_exit", "proper_entrance").
uses_ticket_gate("friend2", "emergency_exit", "proper_entrance").
uses_ticket_gate("friend3", "emergency_exit", "proper_entrance").
violation("friend1", "bag1", "emergency_exit", "proper_entrance").
violation("friend1", "bag2", "emergency_exit", "proper_entrance").
violation("friend2", "bag1", "emergency_exit", "proper_entrance").
violation("friend2", "bag2", "emergency_exit", "proper_entrance").
violation("friend3", "bag1", "emergency_exit", "proper_entrance").
violation("friend3", "bag2", "emergency_exit", "proper_entrance").
.output violation