.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("commuter").
person("friend").
article("groceries").
area("paid_area_side").
area("unpaid_area_side").
paid_area("paid_area_side").
unpaid_area("unpaid_area_side").
transfers("commuter", "groceries", "paid_area_side", "unpaid_area_side").
uses_ticket_gate("commuter", "paid_area_side", "unpaid_area_side").
violation("commuter", "groceries", "paid_area_side", "unpaid_area_side").
.output violation