.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("sarah").
person("emily").
article("ticket").
area("from_area").
area("to_area").
paid_area("from_area").
unpaid_area("to_area").
transfers("emily", "ticket", "from_area", "to_area").
uses_ticket_gate("sarah", "from_area", "to_area").
violation("sarah", "ticket", "from_area", "to_area").
.output violation