.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("man").
person("friend").
article("suitcase").
area("from_side").
area("to_side").
paid_area("to_side").
unpaid_area("from_side").
transfers("man", "suitcase", "from_side", "to_side").
uses_ticket_gate("man", "from_side", "to_side").
violation("man", "suitcase", "from_side", "to_side").
.output violation