.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("student1").
person("student2").
article("textbook").
area("paid_area").
area("unpaid_area").
paid_area("paid_area").
unpaid_area("unpaid_area").
transfers("student1", "textbook", "paid_area", "unpaid_area").
uses_ticket_gate("student1", "paid_area", "unpaid_area").
violation("student1", "textbook", "paid_area", "unpaid_area").
.output violation