.decl person(p: symbol)
.decl article(a: symbol)
.decl area(ar: symbol)
.decl paid_area(ar: symbol)
.decl unpaid_area(ar: symbol)
.decl transfers(p: symbol, a: symbol, from: symbol, to: symbol)
.decl uses_ticket_gate(p: symbol, from: symbol, to: symbol)
.decl violation(p: symbol, a: symbol, from: symbol, to: symbol)

violation(p, a, f, t) :- person(p), article(a), area(f), area(t), transfers(p, a, f, t), ((paid_area(f), unpaid_area(t)); (unpaid_area(f), paid_area(t))), !uses_ticket_gate(p, f, t).
person("friend1").
person("friend2").
article("shopping_bag").
area("emergency_exit").
area("train_station").
paid_area("train_station").
unpaid_area("emergency_exit").
transfers("friend1", "shopping_bag", "emergency_exit", "train_station").
transfers("friend2", "shopping_bag", "emergency_exit", "train_station").
violation("friend1", "shopping_bag", "emergency_exit", "train_station").
violation("friend2", "shopping_bag", "emergency_exit", "train_station").
.output violation