.decl person(p: symbol)
.decl train(t: symbol)
.decl travels(p: symbol, t: symbol)
.decl valid_condition(p: symbol, t: symbol)
.decl violation(p: symbol, t: symbol)

violation(p, t) :- person(p), train(t), travels(p, t), !valid_condition(p, t).
person("teenager1").
person("teenager2").
person("teenager3").
train("escalator").
travels("teenager1", "escalator").
travels("teenager2", "escalator").
travels("teenager3", "escalator").
.output violation