.decl person(p: symbol)
.decl ticket(t: symbol)
.decl damages(p: symbol, t: symbol)
.decl improperly_alters(p: symbol, t: symbol)
.decl violation(p: symbol, t: symbol)

violation(p, t) :- person(p), ticket(t), damages(p, t).
violation(p, t) :- person(p), ticket(t), improperly_alters(p, t).
person("professional1").
ticket("ticket1").
improperly_alters("professional1", "ticket1").
violation("professional1", "ticket1").
.output violation