.decl person(p: symbol)
.decl administrative_charge(c: symbol)
.decl required_to_pay(p: symbol, c: symbol)
.decl has_paid(p: symbol, c: symbol)
.decl violation(p: symbol, c: symbol)

violation(p, c) :- person(p), administrative_charge(c), required_to_pay(p, c), !has_paid(p, c).
person("Sarah").
administrative_charge("toll_booth").
required_to_pay("Sarah", "toll_booth").
violation("Sarah", "toll_booth").
.output violation