.decl person(p: symbol)
.decl administrative_charge(c: symbol)
.decl required_to_pay(p: symbol, c: symbol)
.decl has_paid(p: symbol, c: symbol)
.decl violation(p: symbol, c: symbol)

violation(p, c) :- person(p), administrative_charge(c), required_to_pay(p, c), !has_paid(p, c).
person("commuter1").
administrative_charge("entrance_fee").
required_to_pay("commuter1", "entrance_fee").
.output violation