.decl person(p: symbol)
.decl administrative_charge(c: symbol)
.decl required_to_pay(p: symbol, c: symbol)
.decl has_paid(p: symbol, c: symbol)
.decl violation(p: symbol, c: symbol)

violation(p, c) :- person(p), administrative_charge(c), required_to_pay(p, c), !has_paid(p, c).
person("local_company").
administrative_charge("train_station_permit").
required_to_pay("local_company", "train_station_permit").
.output violation