.decl person(p: symbol)
.decl administrative_charge(c: symbol)
.decl required_to_pay(p: symbol, c: symbol)
.decl has_paid(p: symbol, c: symbol)
.decl violation(p: symbol, c: symbol)

violation(p, c) :- person(p), administrative_charge(c), required_to_pay(p, c), !has_paid(p, c).
person("passenger1").
administrative_charge("reserved_seat_charge").
required_to_pay("passenger1", "reserved_seat_charge").
.output violation