.decl person(p: symbol)
.decl motor_vehicle(mv: symbol)
.decl premises(pr: symbol)
.decl leaves(p: symbol, mv: symbol, pr: symbol)
.decl has_written_permission(p: symbol, pr: symbol)
.decl violation(p: symbol, mv: symbol, pr: symbol)

violation(p, mv, pr) :- person(p), motor_vehicle(mv), premises(pr), leaves(p, mv, pr), !has_written_permission(p, pr).
person("crew_member").
motor_vehicle("maintenance_vehicle").
premises("railway_tracks").
leaves("crew_member", "maintenance_vehicle", "railway_tracks").
violation("crew_member", "maintenance_vehicle", "railway_tracks").
.output violation