.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl sign(s: symbol)
.decl drives(p: symbol, v: symbol)
.decl not_complying(p: symbol, s: symbol)
.decl violation(p: symbol, v: symbol, s: symbol)

violation(p, v, s) :- person(p), vehicle(v), sign(s), drives(p, v), not_complying(p, s).
person("driver").
vehicle("vehicle").
sign("bus_lane_sign").
drives("driver", "vehicle").
not_complying("driver", "bus_lane_sign").
violation("driver", "vehicle", "bus_lane_sign").
.output violation