.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl sign(s: symbol)
.decl drives(p: symbol, v: symbol)
.decl not_complying(p: symbol, s: symbol)
.decl violation(p: symbol, v: symbol, s: symbol)

violation(p, v, s) :- person(p), vehicle(v), sign(s), drives(p, v), not_complying(p, s).
person("driver").
vehicle("car").
sign("loading_zone_for_delivery_vehicles_only").
drives("driver", "car").
not_complying("driver", "loading_zone_for_delivery_vehicles_only").
.output violation