.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl sign(s: symbol)
.decl drives(p: symbol, v: symbol)
.decl not_complying(p: symbol, s: symbol)
.decl violation(p: symbol, v: symbol, s: symbol)

violation(p, v, s) :- person(p), vehicle(v), sign(s), drives(p, v), not_complying(p, s).
person("driver1").
vehicle("car1").
sign("no_u_turn").
drives("driver1", "car1").
not_complying("driver1", "no_u_turn").
violation("driver1", "car1", "no_u_turn").
.output violation