.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl sign(s: symbol)
.decl drives(p: symbol, v: symbol)
.decl not_complying(p: symbol, s: symbol)
.decl violation(p: symbol, v: symbol, s: symbol)

violation(p, v, s) :- person(p), vehicle(v), sign(s), drives(p, v), not_complying(p, s).
person("driver1").
vehicle("vehicle1").
sign("railway_crossing_sign").
drives("driver1", "vehicle1").
not_complying("driver1", "railway_crossing_sign").
violation("driver1", "vehicle1", "railway_crossing_sign").
.output violation