.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl sign(s: symbol)
.decl drives(p: symbol, v: symbol)
.decl not_complying(p: symbol, s: symbol)
.decl violation(p: symbol, v: symbol, s: symbol)

violation(p, v, s) :- person(p), vehicle(v), sign(s), drives(p, v), not_complying(p, s).
person("driver").
person("pedestrian").
vehicle("car").
sign("red_light").
drives("driver", "car").
not_complying("driver", "red_light").
violation("driver", "car", "red_light").
.output violation