.decl person(p: symbol)
.decl premises(pr: symbol)
.decl drives(p: symbol, pr: symbol)
.decl driving_dangerously(p: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), drives(p, pr), driving_dangerously(p, pr).
person("driver1").
premises("railway_tracks").
drives("driver1", "railway_tracks").
driving_dangerously("driver1", "railway_tracks").
violation("driver1", "railway_tracks").
.output violation