.decl person(p: symbol)
.decl premises(pr: symbol)
.decl drives(p: symbol, pr: symbol)
.decl driving_dangerously(p: symbol, pr: symbol)
.decl violation(p: symbol, pr: symbol)

violation(p, pr) :- person(p), premises(pr), drives(p, pr), driving_dangerously(p, pr).
person("driver").
premises("medical_emergency").
drives("driver", "medical_emergency").
driving_dangerously("driver", "medical_emergency").
violation("driver", "medical_emergency").
.output violation