.decl person(p: symbol)
.decl facility(f: symbol)
.decl recreational_facility(f: symbol)
.decl smokes(p: symbol, f: symbol)
.decl violation(p: symbol, f: symbol)

violation(p, f) :- person(p), facility(f), recreational_facility(f), smokes(p, f).
person("friend1").
person("friend2").
person("friend3").
facility("ice_skating_rink").
recreational_facility("ice_skating_rink").
smokes("friend1", "ice_skating_rink").
smokes("friend2", "ice_skating_rink").
smokes("friend3", "ice_skating_rink").
violation("friend1", "ice_skating_rink").
violation("friend2", "ice_skating_rink").
violation("friend3", "ice_skating_rink").
.output violation