.decl person(p: symbol)
.decl facility(f: symbol)
.decl recreational_facility(f: symbol)
.decl smokes(p: symbol, f: symbol)
.decl violation(p: symbol, f: symbol)

violation(p, f) :- person(p), facility(f), recreational_facility(f), smokes(p, f).
person("parent").
facility("playground").
recreational_facility("playground").
smokes("parent", "playground").
violation("parent", "playground").
.output violation