.decl person(p: symbol)
.decl facility(f: symbol)
.decl recreational_facility(f: symbol)
.decl smokes(p: symbol, f: symbol)
.decl violation(p: symbol, f: symbol)

violation(p, f) :- person(p), facility(f), recreational_facility(f), smokes(p, f).
person("man1").
facility("amusement_park").
recreational_facility("amusement_park").
smokes("man1", "amusement_park").
violation("man1", "amusement_park").
.output violation