.decl person(p: symbol)
.decl facility(f: symbol)
.decl educational_facility(f: symbol)
.decl adjacent_area(f: symbol)
.decl smokes(p: symbol, f: symbol)
.decl violation(p: symbol, f: symbol)

violation(p, f) :- person(p), facility(f), (educational_facility(f); adjacent_area(f)), smokes(p, f).
person("student1").
person("student2").
person("student3").
facility("school_parking_lot").
adjacent_area("school_parking_lot").
smokes("student1", "school_parking_lot").
smokes("student2", "school_parking_lot").
.output violation