.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("man1").
area("national_park").
government_statutory_area("national_park").
smokes("man1", "national_park").
violation("man1", "national_park").
.output violation