.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("Sarah").
area("PublicUtilitiesBoardWaterTreatmentPlant").
government_statutory_area("PublicUtilitiesBoardWaterTreatmentPlant").
smokes("Sarah", "PublicUtilitiesBoardWaterTreatmentPlant").
violation("Sarah", "PublicUtilitiesBoardWaterTreatmentPlant").
.output violation