.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("man").
area("Town_Council_park").
government_statutory_area("Town_Council_park").
smokes("man", "Town_Council_park").
violation("man", "Town_Council_park").
.output violation