.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("soldier").
area("designated_smoking_area").
government_statutory_area("designated_smoking_area").
smokes("soldier", "non_designated_area").
violation("soldier", "non_designated_area").
.output violation