.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("friend1").
area("public_park").
government_statutory_area("public_park").
smokes("friend1", "public_park").
violation("friend1", "public_park").
.output violation