.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("woman1").
area("water_treatment_plant").
government_statutory_area("water_treatment_plant").
smokes("woman1", "water_treatment_plant").
violation("woman1", "water_treatment_plant").
.output violation