.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("man1").
area("Jurong_Town_Corporation_park").
government_statutory_area("Jurong_Town_Corporation_park").
smokes("man1", "Jurong_Town_Corporation_park").
.output violation