.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("friend1").
person("friend2").
person("friend3").
area("park").
government_statutory_area("park").
smokes("friend1", "park").
smokes("friend2", "park").
smokes("friend3", "park").
violation("friend1", "park").
violation("friend2", "park").
violation("friend3", "park").
.output violation