.decl person(p: symbol)
.decl area(a: symbol)
.decl government_statutory_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), government_statutory_area(a), smokes(p, a).
person("parent").
person("teacher").
area("school").
area("school_restroom").
government_statutory_area("school").
smokes("parent", "school_restroom").
violation("parent", "school_restroom").
.output violation