.decl person(p: symbol)
.decl area(a: symbol)
.decl specified_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), specified_area(a), smokes(p, a).
person("patient").
person("nurse").
area("hospital_restroom").
specified_area("hospital_restroom").
smokes("patient", "hospital_restroom").
violation("patient", "hospital_restroom").
.output violation