.decl person(p: symbol)
.decl area(a: symbol)
.decl specified_area(a: symbol)
.decl smokes(p: symbol, a: symbol)
.decl violation(p: symbol, a: symbol)

violation(p, a) :- person(p), area(a), specified_area(a), smokes(p, a).
person("patient1").
area("hospital_smoking_area").
specified_area("hospital_smoking_area").
smokes("patient1", "hospital_smoking_area").
violation("patient1", "hospital_smoking_area").
.output violation