.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl specified_transport(v: symbol)
.decl smokes(p: symbol, v: symbol)
.decl violation(p: symbol, v: symbol)

violation(p, v) :- person(p), vehicle(v), specified_transport(v), smokes(p, v).
person("driver").
person("friend1").
vehicle("private_car").
specified_transport("private_car").
smokes("friend1", "private_car").
violation("friend1", "private_car").
.output violation