.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl specified_transport(v: symbol)
.decl smokes(p: symbol, v: symbol)
.decl violation(p: symbol, v: symbol)

violation(p, v) :- person(p), vehicle(v), specified_transport(v), smokes(p, v).
person("friend1").
person("friend2").
person("friend3").
vehicle("private_hire_car").
specified_transport("private_hire_car").
smokes("friend1", "private_hire_car").
smokes("friend2", "private_hire_car").
smokes("friend3", "private_hire_car").
violation("friend1", "private_hire_car").
violation("friend2", "private_hire_car").
violation("friend3", "private_hire_car").
.output violation