.decl person(p: symbol)
.decl vehicle(v: symbol)
.decl specified_transport(v: symbol)
.decl smokes(p: symbol, v: symbol)
.decl violation(p: symbol, v: symbol)

violation(p, v) :- person(p), vehicle(v), specified_transport(v), smokes(p, v).
person("tourist").
vehicle("excursion_bus").
specified_transport("excursion_bus").
smokes("tourist", "excursion_bus").
violation("tourist", "excursion_bus").
.output violation